version: 1.0

deploy:
  # configuration part, which is taken at the FIRST deployment of each branch
  bootstrap:
    # folders that are not copied to IONOS webspace
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
    # commands that are executed at the real webspace NOT at build servers AFTER copying new files
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache


      - php artisan cache:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan statamic:stache:warm
      - php artisan statamic:search:update --all
      - php artisan statamic:static:clear



  # configuration part, which is taken at ALL FURTHER deployments of this branch
  recurring:
    # folders that are not copied to IONOS webspace
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - storage
    # commands that are executed at the real webspace NOT at build servers BEFORE copying new files
    pre-deployment-remote-commands:
      - php artisan down
    # commands that are executed at the real webspace NOT at build servers AFTER copying new files
    post-deployment-remote-commands:
      - tar -xzf git-archive.tar.gz -C .  # Restore.git folder
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - php artisan cache:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan statamic:stache:warm
      - php artisan statamic:search:update --all
      - php artisan statamic:static:clear
      - php artisan up
      - php artisan about
      - php -r 'file_put_contents(getcwd()."/storage/logs/ABS_PATH.txt", getcwd());'
      - php -r 'echo(getcwd());'


# uncomment the following lines to configure cron jobs
#runtime:
#  cron-jobs:
#    - command: my-cron-job-command # the deployment is located at $HOME/htdocs/ to execute a deployed script just prefix it accordingly
#      schedule: 0 5 * * * # run every day at 5:00
